name: Build & Push to container registry
on:
  workflow_call:
    inputs:
      TARGET_FILE:
        description: "Dockerfile to build"
        type: string
        required: false
        default: "Dockerfile"
      TARGET_IMAGE_NAME:
        description: "Docker image name"
        type: string
        required: false
        default: ""
      PLATFORMS:
        description: "Docker image platforms"
        type: string
        required: false
        default: "linux/amd64,linux/arm64/v8"
      RUNNER:
        description: "Runner to use"
        type: string
        required: false
        default: 'ubuntu-latest'

jobs:
  build:
    runs-on: ${{ inputs.RUNNER }}
    steps:
      - name: Check Out Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag name
        id: tags
        if: ${{ github.event_name == 'release' }}
        run: echo ::set-output name=name::${GITHUB_REF##*/}

      - name: Extract flavor
        id: flavor
        run: if [ "${{ github.event_name }}" = "release" ]; then echo ::set-output name=name::; else echo ::set-output name=name::-dev; fi
      
      - id: string
        uses: ASzc/change-string-case-action@d0603cd0a7dd490be678164909f65c7737470a7f # v6
        with:
          string: ${{ github.repository }}

      - name: Generate Docker image metadata
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        id: img_meta
        with:
          flavor: |
            latest=auto
          images: "ghcr.io/${{ inputs.TARGET_IMAGE_NAME || steps.string.outputs.lowercase }}"
          tags: |
            type=ref,event=branch
            type=sha,prefix=,suffix=,format=short

    
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          file: ${{ inputs.TARGET_FILE }}
          context: ./
          platforms: ${{ inputs.PLATFORMS }}
          tags: ${{ steps.img_meta.outputs.tags }}
          labels: ${{ steps.img_meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          secrets: |
            GITHUB_SHA=${{ github.sha }}
            GH_PKG_TOKEN=${{ secrets.GH_TOKEN }}
          
