name: Lint code & compile test


on:
  workflow_call:
    secrets:
      BOT_TOKEN:
        required: true

jobs:
  lint:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

    - name: Setup Node.js
      uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
      with:
        node-version-file: .node-version
        check-latest: true

    - name: Install dependencies
      run: npm ci
      env:
          NPM_CONFIG_USERCONFIG: .ci.npmrc
          GH_PKG_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}

    - name: Lint code
      run: npm run lint

  compile:
    needs: lint
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      - name: Setup Node.js
        uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
        with:
          node-version-file: .node-version
          check-latest: true

      - name: Install dependencies
        run: npm ci
        env:
          NPM_CONFIG_USERCONFIG: .ci.npmrc
          GH_PKG_AUTH_TOKEN: ${{ secrets.BOT_TOKEN }}

      - name: Test compile
        run: npm run compile && rm -rf dist